# -*- coding: utf-8 -*-
"""relevant_transcript.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1krrN1K23KfFYysx6oPJSBqi7fEXBEoIb
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip uninstall -y pinecone-client
# %pip install pinecone
# %pip install sentence-transformers
# %pip install litellm

from getpass import getpass
import os
import asyncio
import uuid
import requests
from dotenv import load_dotenv
from google.adk.agents.llm_agent import LlmAgent
from google.adk.sessions import InMemorySessionService, Session
from google.adk.models.lite_llm import LiteLlm
from google.adk.runners import Runner
from google.adk.tools import FunctionTool
from google.genai import types
from sentence_transformers import SentenceTransformer

"""Initialize embeddings and vector database (Pinecone)"""

load_dotenv()
if "PINECONE_API_KEY" not in os.environ:
    os.environ["PINECONE_API_KEY"] = getpass('Enter your Pinecone API Key: ')

from google.colab import userdata
os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')

from pinecone import Pinecone, ServerlessSpec
pc = Pinecone(api_key=os.environ["PINECONE_API_KEY"])

embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
index_name = "transcript-segments"

APP_NAME   = "relevant_transcript"
USER_ID    = "user_1"
SESSION_ID = "session_001"

"""Indexing - Make the embeddings searchable"""

if index_name not in pc.list_indexes().names():
    pc.create_index(
        name=index_name,
        dimension=384,
        metric="cosine",
        spec=ServerlessSpec(cloud="aws", region="us-east-1")
    )

index = pc.index(index_name)

# hardcoded sample transcript
sample_transcript = [
    {"timestamp_start": "00:00", "timestamp_end": "00:15", "text": "All right, hi everyone. We are getting close to the midterm. It's this Wednesday in two days. Come a little bit early because there's many of us and we need to spread out in the classroom. And don't forget to bring your ID."},
    {"timestamp_start": "00:15", "timestamp_end": "00:30", "text": "Are there any questions or questions about the exam specifically or about the material, like as you did your review this week did anything come up that you would like to discuss? If you have worked on the lab assignments and you are familiar with the schema, this will also help you because the schema will be the same."},
    {"timestamp_start": "00:30", "timestamp_end": "00:45", "text": "All right, if there are no other questions, We will go back to talking about views. So I'll just remind you that what views are. A view is essentially it's a query. It's specified by a query. And it defines a virtual table. The result of the view is a table that we're not really materializing."},
    {"timestamp_start": "00:45", "timestamp_end": "00:55", "text": "But the database stores the definition of the query so we can use the name of the table as if it was a real table. In this example here, we saw, you know, you can define the Disney movies as a view. This is not stored in the database because typically views are not materialized views. There is a tension between updates and query performance."},
    {"timestamp_start": "00:55", "timestamp_end": "01:10", "text": "But where we left off is these examples where we started to think about what it would mean to update a view. And this question is interesting because it's a bit counterintuitive. The usual direction is to say, okay, the data that we store changes, so how does the view change? That's kind of normal."},
    {"timestamp_start": "01:10", "timestamp_end": "01:30", "text": "But now we're asking the opposite question. What happens if someone tries to update a view? And maybe your initial reaction would be that this should not be allowed. But it is allowed in some very special cases where the update can be propagated to the base tables in a straightforward way."}
]

"""Index transcript into Pinecone vector DB"""

print("Indexing transcript segments...")
for i, chunk in enumerate(sample_transcript):
    vector = embedding_model.encode(chunk["text"]).tolist()
    index.upsert(vectors=[(
        f"chunk_{i}",
        vector,
        {"text": chunk["text"], "start": chunk["timestamp_start"], "end": chunk["timestamp_end"]}
    )])
print("Indexing complete!")

"""Search the lecture transcript vector DB for blocks matching query summary"""

def search_transcript(query_summary: str) -> str:
    query_vector = embedding_model.encode(query_summary).tolist()
    results = index.query(vector=query_vector, top_k=2, include_metadata=True)

    context_blocks = []
    for match in results['matches']:
        meta = match['metadata']
        context_blocks.append(f"[{meta['start']} - {meta['end']}]: {meta['text']}")

    return "\n\n".join(context_blocks)

#wrap in ADK function tool
transcript_search_tool = FunctionTool(
    func=search_transcript
)

llm_provider = LiteLlm(model="groq/llama-3.3-70b-versatile")

system_instruction = """
You are an AI Teaching Assistant agent. Your job is to answer a student's question based strictly on the retrieved lecture transcript chunks provided by your search tool.
For every response, you must follow this exact Markdown format:

### **Summary Answer**
[Provide a clear, direct, and concise answer to the student's problem using the transcript data.]

### **Source Timestamp**
[Provide the exact timestamp range(s) where the answer was explicitly found, e.g., `[00:30] - [01:10]`]
"""

agent = LlmAgent(
    name="teaching_assistant_agent",
    model=llm_provider,
    tools=[transcript_search_tool]
)

# agent.llm = llm_provider # Removed: LlmAgent object has no field 'llm'
# agent.system_instruction = system_instruction # Removed: LlmAgent object has no field 'system_instruction'

session_service = InMemorySessionService()
session = Session(
    id=SESSION_ID,
    app_name=APP_NAME,
    user_id=USER_ID
)

runner = Runner(session_service=session_service, app_name=APP_NAME, agent=agent)
student_query = "Student is having trouble understanding what a view is in SQL and specifically if a view changes when a table changes."

full_prompt = f"""
System Instructions:
{system_instruction}

User Query:
{student_query}
"""

formatted_message = types.Content(
    role="user",
    parts=[types.Part.from_text(text=full_prompt)]
)

async def main():
    # Register the session
    active_session = await session_service.create_session(
        app_name=APP_NAME,
        user_id=USER_ID
    )

    print(f"Orchestrating ADK Agent execution step for session: {active_session.id}...")

    # Pass our formatted structured message object into the runner generator
    run_generator = runner.run(
        user_id=USER_ID,
        session_id=active_session.id,
        new_message=formatted_message
    )

    final_text = ""
    for step in run_generator:
        # Check if the step has the 'content' attribute from the GenAI model response
        if hasattr(step, 'content') and step.content and step.content.parts:
            # Join text from all parts if there are multiple, or just grab the first
            final_text = "".join([part.text for part in step.content.parts if hasattr(part, 'text')])
        # Fallbacks for other ADK event structures
        elif hasattr(step, 'response') and hasattr(step.response, 'text'):
            final_text = step.response.text
        elif hasattr(step, 'text'):
            final_text = step.text

    print("\n" + "="*20 + " AGENT OUTPUT " + "="*20)
    if final_text:
        print(final_text)
    else:
        print("Raw Last Step:", step)

# Run it in your Colab cell
await main()