# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1krrN1K23KfFYysx6oPJSBqi7fEXBEoIb
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install pinecone-client
# %pip install sentence-transformers
# %pip install litellm

from getpass import getpass
import os
import asyncio
import uuid
import requests
from dotenv import load_dotenv
from google.adk.agents.llm_agent import Agent
from google.adk.sessions import InMemorySessionService
from google.adk.models.lite_llm import LiteLlm
from google.adk.runners import Runner
from google.adk.tools import FunctionTool
from google.genai import types
load_dotenv()

from pinecone import Pinecone
import time

timestamp = time.time()

pinecone_api_key = getpass('Enter Pinecone API Key: ')

os.environ["PINECONE_API_KEY"] = pinecone_api_key

pc = Pinecone(api_key=os.environ["PINECONE_API_KEY"])

from google.colab import userdata
os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')

APP_NAME   = "relevant_transcript"
USER_ID    = "user_1"
SESSION_ID = "session_001"

if "meeting-memory" not in pc.list_indexes().names():
    pc.create_index(
        name="meeting-memory",
        dimension=384,
        metric="cosine"
    )

index = pc.Index("meeting-memory")

from sentence_transformers import SentenceTransformer

embed_model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

def store_chunk(chunk, chunk_id):
    embedding = embed_model.encode(chunk).tolist()

    index.upsert([
        {
            "id": chunk_id,
            "values": embedding,
            "metadata": {
                "text": chunk,
                "timestamp": time.time(),
                "topic": "cloud costs"  # optional - later use an LLM to classify topic and store as metadata for better retrieval
            }
        }
    ])

# semantic retrieval function - retrieves relevant transcript chunks based on cosine similarity of embeddings
def retrieve_relevant_transcript(query: str) -> str:
# retrieve relevant transcript chunks based on cosine similarity of embeddings from Pinecone index

    query_embedding = embed_model.encode(query).tolist()

    results = index.query(
        vector=query_embedding,
        top_k=3,
        include_metadata=True,
        namespace="meeting_042"
    )

    contexts = [
        match["metadata"]["text"]
        for match in results["matches"]
    ]

    return "\n".join(contexts)

retrieval_tool = FunctionTool(
    retrieve_relevant_transcript
)

from litellm import completion

# retrieval subagent - retrieves relevant transcript chunks and generates insights based on them

meeting_copilot_agent = Agent(
    name="meeting_copilot_agent",

    model=LiteLlm(
        model="groq/llama3-70b-8192"
    ),

    tools=[retrieval_tool],

    instruction="""
You are a real-time AI meeting copilot.

Your job is to:
- analyze live transcript chunks
- retrieve relevant meeting memory
- identify important insights
- detect action items
- surface relevant context
- keep responses concise and useful

When analyzing a transcript chunk:
1. Use the retrieve_relevant_transcript tool
2. Find relevant historical context
3. Generate concise real-time assistance

Focus on:
[Summary of relevant context]
"""
)

# REPLACE WITH ZOOM WEBHOOK STREAM IN PRODUCTION - FOR DEMO PURPOSES, SIMULATE
transcript_stream = [
    "AWS SageMaker costs are growing rapidly.",
    "GPU inference optimization might help.",
    "We should analyze EC2 spot instances."
]

session_service = InMemorySessionService()

runner = Runner(
    agent=meeting_copilot_agent,
    app_name=APP_NAME,
    session_service=session_service
)

async def run_transcript(user_id, session_id):

    for i, chunk in enumerate(transcript_stream):

        store_chunk(chunk, f"chunk-{i}")

        content = types.Content(
            role="user",
            parts=[types.Part(text=chunk)]
        )

        response = await runner.run_async(
            user_id=user_id,
            session_id=session_id,
            new_message=content
        )
        print(response)
    return response